spring.application.name=vehicle-damage-assessment
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/assessmentdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.sbnz=INFO
logging.level.org.drools=WARN
